### ISSUE TITLE
[dogfood] The name of the file devtools/front_end/DebuggerProtocol.js becomes "undefined"

### ISSUE THREAD

**Issue by johnjbarton** [google/qpp#143]
The preprocessor emits one copy of devtools/front_end/DebuggerProtocol.js as devtools/front_end/DebuggerProtocol.js.js but it also sees another copy named by the string "undefined". The second one can be compiled into a data: URL, but the internal value for the file is still "undefined". Using the dataURI string is not going to be pretty, so we need to track down the source of the string "undefined".

**Comment by johnjbarton** [comment]
Seems like at least in this case 'undefined' string come from eval

0  0x000055555917a607 in WebCore::ScriptDebugServer::handleV8DebugEvent (this=0x7ffff7edf6e0, 
    eventDetails=...) at ../../third_party/WebKit/Source/bindings/v8/ScriptDebugServer.cpp:568
#1  0x0000555559179fc6 in WebCore::ScriptDebugServer::v8DebugEventCallback (eventDetails=...)
    at ../../third_party/WebKit/Source/bindings/v8/ScriptDebugServer.cpp:511
#2  0x0000555559e804a1 in v8::internal::Debugger::CallCEventCallback (this=0x3060a256f220, 
    event=v8::BeforeCompile, exec_state=..., event_data=..., client_data=0x0) at ../../v8/src/debug.cc:2949
#3  0x0000555559e803e7 in v8::internal::Debugger::CallEventCallback (this=0x3060a256f220, 
    event=v8::BeforeCompile, exec_state=..., event_data=..., client_data=0x0) at ../../v8/src/debug.cc:2928
#4  0x0000555559e802b7 in v8::internal::Debugger::ProcessDebugEvent (this=0x3060a256f220, 
    event=v8::BeforeCompile, event_data=..., auto_continue=true) at ../../v8/src/debug.cc:2905
#5  0x0000555559e7fc9f in v8::internal::Debugger::OnBeforeCompile (this=0x3060a256f220, script=...)
    at ../../v8/src/debug.cc:2773
#6  0x0000555559e6ae8b in v8::internal::MakeFunctionInfo (info=0x7fffffffb4d0)
    at ../../v8/src/compiler.cc:518
#7  0x0000555559e6bc16 in v8::internal::Compiler::CompileEval (source=..., context=..., is_global=true, 
    language_mode=v8::internal::CLASSIC_MODE, restriction=v8::internal::NO_PARSE_RESTRICTION, 
    scope_position=-1) at ../../v8/src/compiler.cc:714
#8  0x000055555a097552 in v8::internal::Runtime_CompileString (args=..., isolate=0x7ffff7e9d020)
    at ../../v8/src/runtime.cc:864
